/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectteaminthanin;

import com.mycompany.projectteaminthanin.DaoModel.DaoCustomer;
import com.mycompany.projectteaminthanin.DaoModel.DaoReceipt;
import com.mycompany.projectteaminthanin.Menu.CoffeePanel;
import com.mycompany.projectteaminthanin.Menu.FrameRegister;
import com.mycompany.projectteaminthanin.Menu.FruitPanel;
import com.mycompany.projectteaminthanin.Menu.TeaAndCocoaPanel;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.Product;
import model.Receipt;
import model.User;

/**
 *
 * @author AuyouknoW
 */
public class Point_of_sell extends javax.swing.JPanel {

    public static DefaultTableModel CartModel;
    public boolean beMember = false;
    public ArrayList<Cart> cart = new ArrayList<>();
    public double total = 0;
    MainMenuPanel mainmenu;
    /**
     * Creates new form Point_of_sell
     */
    public Point_of_sell(MainMenuPanel mainmenu) {
        initComponents();
        disableCheckOut();
        this.mainmenu = mainmenu;
        scpmenu.setViewportView(new CoffeePanel(this));
        CartModel = (DefaultTableModel) table.getModel();
        btnDelete.setEnabled(false);

    }

    public DefaultTableModel getCartModel() {
        return CartModel;
    }

    public void setCartModel(DefaultTableModel CartModel) {
        this.CartModel = CartModel;
    }

    public void disableCheckOut() {
        txtCashChange.setText("Cash : ");
        txtCashChange.setVisible(false);
        tfcash.setVisible(false);
        tfChange.setVisible(false);
        btnPrintReceipt.setVisible(false);
        btnPrintReceipt.setEnabled(false);
        
    }

    public void enableCheckOut() {
        txtCashChange.setVisible(true);
        tfcash.setVisible(true);
        

        disableLeft();
        disableScreen();
    }

    public void disableLeft() {
        table.setEnabled(false);
        tfSearch.setEnabled(false);
        btnRegister.setEnabled(false);
        btnDelete.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void disableScreen() {
        scpmenu.setViewportView(new ClearPanel());
        btnPay.setEnabled(false);
        btnCoffee.setEnabled(false);
        btnFriut.setEnabled(false);
        btnTea.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCoffee2 = new javax.swing.JButton();
        scrMenuPanel = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtMember = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        pnlShowname = new javax.swing.JPanel();
        txtNameMember = new javax.swing.JLabel();
        pnlTotal = new javax.swing.JPanel();
        txtTotal = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tableCart = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnPrintReceipt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblStatusMember = new javax.swing.JLabel();
        scpmenu = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        btnCoffee = new javax.swing.JButton();
        btnTea = new javax.swing.JButton();
        btnFriut = new javax.swing.JButton();
        tfcash = new javax.swing.JTextField();
        txtCashChange = new javax.swing.JLabel();
        tfChange = new javax.swing.JTextField();

        btnCoffee2.setText("COFFEE");

        jPanel1.setBackground(new java.awt.Color(159, 133, 116));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        txtMember.setBackground(new java.awt.Color(255, 255, 255));
        txtMember.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMember.setText("MEMBER INFORMATION");

        tfSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSearch.setText("SEARCH");
        tfSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSearchMouseClicked(evt);
            }
        });
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        txtNameMember.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtNameMember.setText("Name :");

        javax.swing.GroupLayout pnlShownameLayout = new javax.swing.GroupLayout(pnlShowname);
        pnlShowname.setLayout(pnlShownameLayout);
        pnlShownameLayout.setHorizontalGroup(
            pnlShownameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShownameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNameMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlShownameLayout.setVerticalGroup(
            pnlShownameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShownameLayout.createSequentialGroup()
                .addComponent(txtNameMember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        txtTotal.setBackground(new java.awt.Color(153, 153, 153));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotal.setText("TOTAL");

        javax.swing.GroupLayout pnlTotalLayout = new javax.swing.GroupLayout(pnlTotal);
        pnlTotal.setLayout(pnlTotalLayout);
        pnlTotalLayout.setHorizontalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTotalLayout.setVerticalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnRegister.setBackground(new java.awt.Color(153, 153, 153));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(228, 55, 55));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 0));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Amount", "Price"
            }
        ));
        table.setRowHeight(25);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        tableCart.setViewportView(table);

        btnPrintReceipt.setBackground(new java.awt.Color(255, 255, 255));
        btnPrintReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrintReceipt.setText("PrintReceipt");
        btnPrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReceiptActionPerformed(evt);
            }
        });

        jLabel1.setText("Discount :");

        lblStatusMember.setForeground(new java.awt.Color(255, 0, 51));
        lblStatusMember.setText("0%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatusMember)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tableCart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfSearch)
                            .addComponent(pnlShowname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrintReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlShowname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(jLabel1)
                    .addComponent(lblStatusMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableCart, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 919, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        scpmenu.setViewportView(jPanel3);

        btnPay.setBackground(new java.awt.Color(153, 153, 0));
        btnPay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Confirm");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnCoffee.setBackground(new java.awt.Color(91, 103, 63));
        btnCoffee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCoffee.setForeground(new java.awt.Color(255, 255, 255));
        btnCoffee.setText("COFFEE");
        btnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffeeActionPerformed(evt);
            }
        });

        btnTea.setBackground(new java.awt.Color(91, 103, 63));
        btnTea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTea.setForeground(new java.awt.Color(255, 255, 255));
        btnTea.setText("TEA & COCOA");
        btnTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeaActionPerformed(evt);
            }
        });

        btnFriut.setBackground(new java.awt.Color(91, 103, 63));
        btnFriut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFriut.setForeground(new java.awt.Color(255, 255, 255));
        btnFriut.setText("FRUIT DRINK");
        btnFriut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFriutActionPerformed(evt);
            }
        });

        tfcash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfcash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfcash.setText("cash");
        tfcash.setPreferredSize(new java.awt.Dimension(74, 28));
        tfcash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfcashMouseClicked(evt);
            }
        });
        tfcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcashActionPerformed(evt);
            }
        });

        txtCashChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtCashChange.setForeground(new java.awt.Color(255, 255, 255));
        txtCashChange.setText("change money :");

        tfChange.setEditable(false);
        tfChange.setBackground(new java.awt.Color(255, 255, 255));
        tfChange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfChange.setText("change");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCashChange)
                                .addGap(18, 18, 18)
                                .addComponent(tfcash, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(tfChange, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scpmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTea, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFriut, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTea, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFriut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCashChange, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfcash, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfChange, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        scrMenuPanel.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrMenuPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrMenuPanel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffeeActionPerformed
        scpmenu.setViewportView(new CoffeePanel(this));
    }//GEN-LAST:event_btnCoffeeActionPerformed

    private void btnTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeaActionPerformed
        scpmenu.setViewportView(new TeaAndCocoaPanel(this));
    }//GEN-LAST:event_btnTeaActionPerformed

    private void btnFriutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriutActionPerformed
        scpmenu.setViewportView(new FruitPanel(this));
    }//GEN-LAST:event_btnFriutActionPerformed
    
    
    DaoCustomer daoCus = new DaoCustomer();
    UserService us = new UserService();
    Customer currentCustomer = daoCus.get(6);
    User currentEmp = us.getCurrentUser();

    public double Discount = 0;
    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        String tel = tfSearch.getText();

        for (Customer c : daoCus.getAll()) {
            if (tel.equals(c.getPhone())) {
                txtNameMember.setText("Name : " + c.getName());
                currentCustomer = c;
                beMember = true;
                tfSearch.setEnabled(false);
                btnRegister.setEnabled(false);
                lblStatusMember.setForeground(Color.GREEN);
                lblStatusMember.setText("10%");
                System.out.println("MemberStatus : " + beMember);
                System.out.println("Customer : " + currentCustomer.getName());
                System.out.println("EMP : " + currentEmp.getEmployee().getName());
                System.out.println("");
                return;
            }
        }

        System.out.println("MemberStatus : " + beMember);
        System.out.println("Customer : " + currentCustomer.getName());
        System.out.println("EMP : " + currentEmp.getEmployee().getName());
        System.out.println("");
        txtNameMember.setText("Not Found");
        tfSearch.setText("");
    }//GEN-LAST:event_tfSearchActionPerformed

    public void setlblTotal(double total) {
        txtTotal.setText("Total : " + total);
    }
    private void tfSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchMouseClicked
        tfSearch.setText("");
    }//GEN-LAST:event_tfSearchMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        FrameRegister rgf = new FrameRegister();
        rgf.newScreen();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        if (CartModel.getRowCount() > 0) {
            if (beMember == true) {
                Discount = total * 0.01;
                Discount = Math.ceil(Discount);
                total -= Discount;
                txtTotal.setText("Discounted Total : " + total);

            }
            System.out.println(cart);
            System.out.println("Price : " + total);
            enableCheckOut();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Please Select Product First.", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnPayActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cart.clear();
        int cTable = table.getRowCount();
        for (int i = 0; i < cTable; i++) {
            CartModel.removeRow(0);
        }
        total = 0;
        txtTotal.setText("Total : " + total);
    }//GEN-LAST:event_btnClearActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int choose = table.getSelectedRow();
        CartModel.removeRow(choose);
        Cart lastTotal = cart.remove(choose);
        total -= lastTotal.getAmount() * lastTotal.getProduct().getPrice();
        txtTotal.setText("Total : " + total);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tfcashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfcashMouseClicked
        tfcash.setText("");
    }//GEN-LAST:event_tfcashMouseClicked
    double cash = 0;
    double change = 0;
    public int lastId = 0;
    private void tfcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcashActionPerformed
        cash = Double.parseDouble(tfcash.getText());
        if (total <= cash) {
            btnPrintReceipt.setVisible(true);
            btnPrintReceipt.setEnabled(true);
            Receipt rep = new Receipt(currentEmp.getEmployee(), currentCustomer);
            for (int i = 0; i < cart.size(); i++) {
                rep.addReceiptDetail(cart.get(i).getProduct(), cart.get(i).getAmount());
            }
            rep.setTotal(total);
            rep.setCash(cash);
            change = cash - total;
            rep.setChange(change);
            DaoReceipt daoReceipt = new DaoReceipt();
            tfcash.setVisible(false);
            txtCashChange.setText("Change : ");
            tfChange.setVisible(true);
            tfChange.setText("" + change);

            //////////////////////////////////////////////////////////////////////
            lastId = daoReceipt.add(rep);
            //////////////////////////////////////////////////////////////////////
            System.out.println(lastId);

        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Cash < Total", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_tfcashActionPerformed

    private void btnPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptActionPerformed
        PrintReceipt pr = new PrintReceipt(new javax.swing.JFrame(), true, this,mainmenu);
        pr.setVisible(true);

    }//GEN-LAST:event_btnPrintReceiptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCoffee;
    private javax.swing.JButton btnCoffee2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFriut;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPrintReceipt;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnTea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblStatusMember;
    private javax.swing.JPanel pnlShowname;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JScrollPane scpmenu;
    private javax.swing.JScrollPane scrMenuPanel;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableCart;
    private javax.swing.JTextField tfChange;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfcash;
    private javax.swing.JLabel txtCashChange;
    private javax.swing.JLabel txtMember;
    private javax.swing.JLabel txtNameMember;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
