/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectteaminthanin;

import com.mycompany.projectteaminthanin.DaoModel.DaoReceipt;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import model.ReceiptDetail;

/**
 *
 * @author ROG
 */
public class PrintReceipt extends javax.swing.JDialog {
    Point_of_sell POS;
    MainMenuPanel mainmenu;
    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt(java.awt.Frame parent, boolean modal,Point_of_sell POS,MainMenuPanel mainmenu) {
        super(parent, modal);
        initComponents();
        
        this.POS = POS;
        this.mainmenu = mainmenu;
       DaoReceipt daoShow = new DaoReceipt();
        int table = POS.lastId;
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            txtDetail.setText(txtDetail.getText() + "                       ร้านกาแฟ Inthanin                \n");
            txtDetail.setText(txtDetail.getText() + "                   สาขา  มหาวิทยาลัยบูรพา            \n");
            txtDetail.setText(txtDetail.getText() + "รหัสใบเสร็จเลขที่\t" + daoShow.get(table).getRep_id() + "   \n");
            txtDetail.setText(txtDetail.getText() + "ผู้ขาย \t" + daoShow.get(table).getEmployee().getName() + "\n");
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            int i = 1;
            int amount = 0;
            double total = 0;
            for (ReceiptDetail c : daoShow.get(table).getReceiptDetail()) {
                txtDetail.setText(txtDetail.getText() + c.getAmount() + "  " + c.getProduct().getProductName() + "\t" + c.getProduct().getPrice() * c.getAmount() + "\n");
                amount += c.getAmount();
                i++;
                total+=c.getProduct().getPrice() * c.getAmount();
            }
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            txtDetail.setText(txtDetail.getText() + "ยอดสุทธิ " + amount);
            txtDetail.setText(txtDetail.getText() + "\tPrice\t" + total + " Baht\n");
            txtDetail.setText(txtDetail.getText() + "\tDiscount\t" + (total-daoShow.get(table).getTotal()) + " Baht\n\n");
            
            txtDetail.setText(txtDetail.getText() + "\tTotal\t" + daoShow.get(table).getTotal() + " Baht\n");
            txtDetail.setText(txtDetail.getText() + "\tCash\t" + daoShow.get(table).getCash() + " Baht\n");
            txtDetail.setText(txtDetail.getText() + "\tChange\t" + daoShow.get(table).getChange() + " Baht\n");
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            txtDetail.setText(txtDetail.getText() + "                      Inthanin Coffee                      \n");
            txtDetail.setText(txtDetail.getText() + "                    Tel. 088-088-0888 \n");
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            txtDetail.setText(txtDetail.getText() + daoShow.get(table).getDate());
    }


    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        btnReceiptConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDetail.setEditable(false);
        txtDetail.setColumns(20);
        txtDetail.setFont(new java.awt.Font("AngsanaUPC", 0, 18)); // NOI18N
        txtDetail.setRows(5);
        jScrollPane1.setViewportView(txtDetail);

        btnReceiptConfirm.setBackground(new java.awt.Color(102, 204, 0));
        btnReceiptConfirm.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnReceiptConfirm.setText("Confirm");
        btnReceiptConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(btnReceiptConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReceiptConfirm)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReceiptConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptConfirmActionPerformed
        mainmenu.resetPointOfSell();
        this.dispose();
    }//GEN-LAST:event_btnReceiptConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrintReceipt dialog = new PrintReceipt(new javax.swing.JFrame(), true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReceiptConfirm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDetail;
    // End of variables declaration//GEN-END:variables
}
