/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OtherPage;

import com.mycompany.projectteaminthanin.DaoModel.DaoCustomer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Customer;

/**
 *
 * @author NITRO 5
 */
public class TableCustomer extends javax.swing.JPanel {

    private ArrayList<Customer> customerList;
    private Customertablemodel model;
    Customer editedCustomer;

    /**
     * Creates new form TableCustomer
     */
    public TableCustomer() {
        initComponents();
        DaoCustomer dao = new DaoCustomer();
        initForm();
        loadTable(dao);
    }

    public void initForm() {
        lblidCustomer.setEnabled(false);
        txtnameCustomer.setEnabled(false);
        txtphoneCustomer.setEnabled(false);
        txtbirthdayCustomer.setEnabled(false);
        btnsaveCustomer.setEnabled(false);
        btnCancelCustomer.setEnabled(false);
    }

    public void refreshTable() {
        DaoCustomer dao = new DaoCustomer();
        ArrayList<Customer> newList = dao.getAll();
        customerList.clear();
        customerList.addAll(newList);
        tblCustomer.revalidate();
        tblCustomer.repaint();
    }

    public void clearEditForm() {
        editedCustomer = null;
        lblshowidCustomer.setText("");
        txtnameCustomer.setText("");
        txtphoneCustomer.setText("");
        txtbirthdayCustomer.setText("");
        initForm();

    }

    public void loadFormToCustomer() {
        editedCustomer.setName(txtnameCustomer.getText());
        editedCustomer.setPhone(txtphoneCustomer.getText());
        editedCustomer.setBirthDay(txtbirthdayCustomer.getText());
    }

    public void loadTable(DaoCustomer dao) {
        customerList = dao.getAll();
        model = new Customertablemodel(customerList);
        tblCustomer.setModel(model);
    }

    public void loadCustomerToForm() {
        if (editedCustomer.getCustomerId() >= 0) {
            lblshowidCustomer.setText("" + editedCustomer.getCustomerId());
        }
        txtnameCustomer.setText(editedCustomer.getName());
        txtphoneCustomer.setText(editedCustomer.getPhone());
        txtbirthdayCustomer.setText("" + editedCustomer.getBirthDay());
        txtnameCustomer.setEnabled(true);
        txtphoneCustomer.setEnabled(true);
        txtbirthdayCustomer.setEnabled(true);
        btnsaveCustomer.setEnabled(true);
        btnCancelCustomer.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblnameCustomer = new javax.swing.JLabel();
        lblidCustomer = new javax.swing.JLabel();
        lblPhoneCustomer = new javax.swing.JLabel();
        lblbirthDayCustomer = new javax.swing.JLabel();
        txtnameCustomer = new javax.swing.JTextField();
        txtphoneCustomer = new javax.swing.JTextField();
        txtbirthdayCustomer = new javax.swing.JTextField();
        lblshowidCustomer = new javax.swing.JLabel();
        btnsaveCustomer = new javax.swing.JButton();
        btnCancelCustomer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(207, 192, 183));
        setPreferredSize(new java.awt.Dimension(888, 469));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCustomer);

        jPanel1.setBackground(new java.awt.Color(112, 84, 62));

        lblnameCustomer.setText("Name   : ");

        lblidCustomer.setText("ID     :");

        lblPhoneCustomer.setText("Phone   :");

        lblbirthDayCustomer.setText("BirthDay   : ");

        txtphoneCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneCustomerActionPerformed(evt);
            }
        });

        lblshowidCustomer.setText("?");

        btnsaveCustomer.setBackground(new java.awt.Color(0, 153, 153));
        btnsaveCustomer.setText("Save");
        btnsaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveCustomerActionPerformed(evt);
            }
        });

        btnCancelCustomer.setBackground(new java.awt.Color(204, 102, 0));
        btnCancelCustomer.setText("Cancel");
        btnCancelCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblbirthDayCustomer)
                            .addComponent(lblnameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblidCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsaveCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelCustomer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblshowidCustomer)
                            .addComponent(txtphoneCustomer)
                            .addComponent(txtnameCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtbirthdayCustomer))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidCustomer)
                    .addComponent(lblshowidCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnameCustomer)
                    .addComponent(txtnameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneCustomer)
                    .addComponent(txtphoneCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbirthDayCustomer)
                    .addComponent(txtbirthdayCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsaveCustomer)
                    .addComponent(btnCancelCustomer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(110, 95, 56));

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtSearch.setText("Search");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtphoneCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneCustomerActionPerformed

    private void btnsaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveCustomerActionPerformed
        loadFormToCustomer();
        DaoCustomer dao = new DaoCustomer();
        if (editedCustomer.getCustomerId() >= 0) {
            dao.update(editedCustomer);
        } else {
            dao.add(editedCustomer);
        }
        refreshTable();
        clearEditForm();
    }//GEN-LAST:event_btnsaveCustomerActionPerformed

    private void btnCancelCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelCustomerActionPerformed
        clearEditForm();
    }//GEN-LAST:event_btnCancelCustomerActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        editedCustomer = new Customer(-1, " ", "", "");
        loadCustomerToForm();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (tblCustomer.getSelectedRow() >= 0) {
            editedCustomer = customerList.get(tblCustomer.getSelectedRow());
            loadCustomerToForm();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (tblCustomer.getSelectedRow() >= 0) {
                DaoCustomer dao = new DaoCustomer();
                editedCustomer = customerList.get(tblCustomer.getSelectedRow());
                dao.delete(editedCustomer.getCustomerId());
            }
            refreshTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        model = (Customertablemodel) tblCustomer.getModel();
        TableRowSorter <Customertablemodel> trs = new TableRowSorter<>(model);
        tblCustomer.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(txtSearch.getText()));
    }//GEN-LAST:event_txtSearchKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancelCustomer;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnsaveCustomer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPhoneCustomer;
    private javax.swing.JLabel lblbirthDayCustomer;
    private javax.swing.JLabel lblidCustomer;
    private javax.swing.JLabel lblnameCustomer;
    private javax.swing.JLabel lblshowidCustomer;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtbirthdayCustomer;
    private javax.swing.JTextField txtnameCustomer;
    private javax.swing.JTextField txtphoneCustomer;
    // End of variables declaration//GEN-END:variables
private class Customertablemodel extends AbstractTableModel {

        private final ArrayList<Customer> data;

        String[] columnName = {"ID", "Name", "Phone", "Birthday"};

        private Customertablemodel(ArrayList<Customer> data) {
            this.data = data;
        }

        @Override
        public int getRowCount() {
            return this.data.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Customer customer = this.data.get(rowIndex);
            if (columnIndex == 0) {
                return customer.getCustomerId();
            }
            if (columnIndex == 1) {
                return customer.getName();
            }
            if (columnIndex == 2) {
                return customer.getPhone();
            }
            if (columnIndex == 3) {
                return customer.getBirthDay();
            }
            return "";
        }

        @Override
        public String getColumnName(int column) {
            return columnName[column];
        }

    }

}
