/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OtherPage;

import com.mycompany.projectteaminthanin.DaoModel.DaoReceipt;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import model.Receipt;
import model.ReceiptDetail;

/**
 *
 * @author NITRO 5
 */
public class TableReceiptPanel extends javax.swing.JPanel {

    private ArrayList<Receipt> receiptList;
    private ReceiptTablemodel model;
    Receipt editedReceipt;

    /**
     * Creates new form TableStock
     */
    public TableReceiptPanel() {
        initComponents();
        DaoReceipt dao = new DaoReceipt();
        btnDelete.setEnabled(false);
        txtDetail.setVisible(false);
        jScrollPane2.setVisible(false);
        loadTable(dao);
    }

    public void refreshTable() {
        DaoReceipt dao = new DaoReceipt();
        ArrayList<Receipt> newList = dao.getAll();
        receiptList.clear();
        receiptList.addAll(newList);
        tblReceipt.revalidate();
        tblReceipt.repaint();
    }

    public void loadTable(DaoReceipt dao) {
        receiptList = dao.getAll();
        model = new ReceiptTablemodel(receiptList);
        tblReceipt.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReceipt = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(207, 192, 183));
        setPreferredSize(new java.awt.Dimension(888, 469));

        tblReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReceiptMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReceipt);

        jPanel2.setBackground(new java.awt.Color(110, 95, 56));

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addContainerGap())
        );

        txtDetail.setEditable(false);
        txtDetail.setColumns(20);
        txtDetail.setFont(new java.awt.Font("AngsanaUPC", 0, 18)); // NOI18N
        txtDetail.setRows(5);
        jScrollPane2.setViewportView(txtDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (tblReceipt.getSelectedRow() >= 0) {
                DaoReceipt dao = new DaoReceipt();
                editedReceipt = receiptList.get(tblReceipt.getSelectedRow());
                dao.delete(editedReceipt.getRep_id());
            }
            refreshTable();
        }
        btnDelete.setEnabled(false);
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void showDetail() {
        DaoReceipt daoShow = new DaoReceipt();
        txtDetail.setText("");
        if (tblReceipt.getSelectedRow() >= 0) {
            int table = receiptList.get(tblReceipt.getSelectedRow()).getRep_id();
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            txtDetail.setText(txtDetail.getText() + "                       ร้านกาแฟ Inthanin                \n");
            txtDetail.setText(txtDetail.getText() + "                   สาขา  มหาวิทยาลัยบูรพา            \n");
            txtDetail.setText(txtDetail.getText() + "รหัสใบเสร็จเลขที่\t" + daoShow.get(table).getRep_id() + "   \n");
            txtDetail.setText(txtDetail.getText() + "ผู้ขาย \t" + daoShow.get(table).getEmployee().getName() + "\n");
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            int i = 1;
            int amount = 0;
            double total = 0;
            for (ReceiptDetail c : daoShow.get(table).getReceiptDetail()) {
                txtDetail.setText(txtDetail.getText() + c.getAmount() + "  " + c.getProduct().getProductName() + "\t" + c.getProduct().getPrice() * c.getAmount() + "\n");
                amount += c.getAmount();
                i++;
                total+=c.getProduct().getPrice() * c.getAmount();
            }
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            txtDetail.setText(txtDetail.getText() + "ยอดสุทธิ " + amount);
            txtDetail.setText(txtDetail.getText() + "\tPrice\t" + total + " Baht\n");
            txtDetail.setText(txtDetail.getText() + "\tDiscount\t" + (total-daoShow.get(table).getTotal()) + " Baht\n\n");
            
            txtDetail.setText(txtDetail.getText() + "\tTotal\t" + daoShow.get(table).getTotal() + " Baht\n");
            txtDetail.setText(txtDetail.getText() + "\tCash\t" + daoShow.get(table).getCash() + " Baht\n");
            txtDetail.setText(txtDetail.getText() + "\tChange\t" + daoShow.get(table).getChange() + " Baht\n");
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            txtDetail.setText(txtDetail.getText() + "                      Inthanin Coffee                      \n");
            txtDetail.setText(txtDetail.getText() + "                    Tel. 088-088-0888 \n");
            txtDetail.setText(txtDetail.getText() + "------------------------------------------------------\n");
            txtDetail.setText(txtDetail.getText() + daoShow.get(table).getDate());
        }
        refreshTable();
    }

    private void tblReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReceiptMouseClicked
        btnDelete.setEnabled(true);
        jScrollPane2.setVisible(true);
        txtDetail.setVisible(true);
        showDetail();
    }//GEN-LAST:event_tblReceiptMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblReceipt;
    private javax.swing.JTextArea txtDetail;
    // End of variables declaration//GEN-END:variables
private class ReceiptTablemodel extends AbstractTableModel {

        private final ArrayList<Receipt> data;

        String[] columnName = {"ID", "EMP_ID", "DATE", "CUS_ID", "Total", "Cash", "Change"};

        private ReceiptTablemodel(ArrayList<Receipt> data) {
            this.data = data;
        }

        @Override
        public int getRowCount() {
            return this.data.size();
        }

        @Override
        public int getColumnCount() {
            return 7;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Receipt receipt = this.data.get(rowIndex);
            if (columnIndex == 0) {
                return receipt.getRep_id();
            }
            if (columnIndex == 1) {
                return receipt.getEmpID();
            }
            if (columnIndex == 2) {
                return receipt.getDate();
            }
            if (columnIndex == 3) {
                return receipt.getCusID();
            }
            if (columnIndex == 4) {
                return receipt.getTotal();
            }
            if (columnIndex == 5) {
                return receipt.getCash();
            }
            if (columnIndex == 6) {
                return receipt.getChange();
            }
            return "";
        }

        @Override
        public String getColumnName(int column) {
            return columnName[column];
        }

    }

}
