/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OtherPage;

import com.mycompany.projectteaminthanin.DaoModel.DaoStock;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import model.Stock;

/**
 *
 * @author NITRO 5
 */
public class TableReceiptPanel extends javax.swing.JPanel {

    private ArrayList<Stock> stockList;
    private Stocktablemodel model;
    Stock editedStock;
    /**
     * Creates new form TableStock
     */
    public TableReceiptPanel() {
        initComponents();
        DaoStock dao = new DaoStock();
        initForm();
        loadTable(dao);
    }
     public void initForm() {
        lblidReceipt.setEnabled(false);
        txtnameReceipt.setEnabled(false);
        txtamountReceipt.setEnabled(false);
        txtpriceReceipt.setEnabled(false);
        btnsaveReceipt.setEnabled(false);
        btncancleReceipt.setEnabled(false);
    }
     public void refreshTable() {
        DaoStock dao = new DaoStock();
        ArrayList<Stock> newList = dao.getAll();
        stockList.clear();
        stockList.addAll(newList);
        tblReceipt.revalidate();
        tblReceipt.repaint();
    }
      public void clearEditForm() {
        editedStock = null;
        lblshowidReceipt.setText("");
        txtnameReceipt.setText("");
        txtamountReceipt.setText("");
        txtpriceReceipt.setText("");
        initForm();

    }
      public void loadFormToStock() {
        editedStock.setStockprod_name(txtnameReceipt.getText());
        editedStock.setAmount(Integer.parseInt(txtamountReceipt.getText()));
        editedStock.setPrice(Double.parseDouble(txtpriceReceipt.getText()));
    }
      public void loadTable(DaoStock dao) {
        stockList = dao.getAll();
        model = new Stocktablemodel(stockList);
        tblReceipt.setModel(model);
    }
     public void loadStockToForm() {
        if (editedStock.getStock_id() >= 0) {
            lblshowidReceipt.setText("" + editedStock.getStock_id());
        }
        txtnameReceipt.setText(editedStock.getStockprod_name());
        txtamountReceipt.setText(editedStock.getAmount()+"");
        txtpriceReceipt.setText("" + editedStock.getPrice());
        txtnameReceipt.setEnabled(true);
        txtamountReceipt.setEnabled(true);
        txtpriceReceipt.setEnabled(true);
        btnsaveReceipt.setEnabled(true);
        btncancleReceipt.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReceipt = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblnameReceipt = new javax.swing.JLabel();
        lblidReceipt = new javax.swing.JLabel();
        lbamountReceipt = new javax.swing.JLabel();
        lblpriceReceipt = new javax.swing.JLabel();
        txtnameReceipt = new javax.swing.JTextField();
        txtamountReceipt = new javax.swing.JTextField();
        txtpriceReceipt = new javax.swing.JTextField();
        lblshowidReceipt = new javax.swing.JLabel();
        btnsaveReceipt = new javax.swing.JButton();
        btncancleReceipt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(888, 469));

        tblReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReceipt);

        lblnameReceipt.setText("Name : ");

        lblidReceipt.setText("ID      :");

        lbamountReceipt.setText("Amount :");

        lblpriceReceipt.setText("Price   : ");

        txtamountReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountReceiptActionPerformed(evt);
            }
        });

        lblshowidReceipt.setText("?");

        btnsaveReceipt.setText("Save");
        btnsaveReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveReceiptActionPerformed(evt);
            }
        });

        btncancleReceipt.setText("Cancle");
        btncancleReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancleReceiptActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Receipt Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblnameReceipt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbamountReceipt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblidReceipt)
                    .addComponent(lblpriceReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsaveReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancleReceipt)
                        .addContainerGap(654, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblshowidReceipt)
                            .addComponent(txtamountReceipt)
                            .addComponent(txtnameReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtpriceReceipt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblidReceipt)
                            .addComponent(lblshowidReceipt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnameReceipt)
                            .addComponent(txtnameReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbamountReceipt)
                            .addComponent(txtamountReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpriceReceipt)
                            .addComponent(txtpriceReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsaveReceipt)
                    .addComponent(btncancleReceipt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtamountReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountReceiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountReceiptActionPerformed

    private void btnsaveReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveReceiptActionPerformed
        loadFormToStock();
        DaoStock dao = new DaoStock();
        if (editedStock.getStock_id() >= 0) {
            dao.update(editedStock);
        } else {
            dao.add(editedStock);
        }
        refreshTable();
        clearEditForm();
    }//GEN-LAST:event_btnsaveReceiptActionPerformed

    private void btncancleReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancleReceiptActionPerformed
        clearEditForm();
    }//GEN-LAST:event_btncancleReceiptActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (tblReceipt.getSelectedRow() >= 0) {
            editedStock = stockList.get(tblReceipt.getSelectedRow());
            loadStockToForm();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        if (tblReceipt.getSelectedRow() >= 0) {
            DaoStock dao = new DaoStock();
            editedStock = stockList.get(tblReceipt.getSelectedRow());
            dao.delete(editedStock.getStock_id());
        }
        refreshTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btncancleReceipt;
    private javax.swing.JButton btnsaveReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbamountReceipt;
    private javax.swing.JLabel lblidReceipt;
    private javax.swing.JLabel lblnameReceipt;
    private javax.swing.JLabel lblpriceReceipt;
    private javax.swing.JLabel lblshowidReceipt;
    private javax.swing.JTable tblReceipt;
    private javax.swing.JTextField txtamountReceipt;
    private javax.swing.JTextField txtnameReceipt;
    private javax.swing.JTextField txtpriceReceipt;
    // End of variables declaration//GEN-END:variables
private class Stocktablemodel extends AbstractTableModel{
   
    
    private final ArrayList<Stock> data;
       
    String[] columnName = {"ID", "Name", "Amount", "Price"};

        private Stocktablemodel(ArrayList<Stock> data) {
            this.data=data;
        }

        @Override
        public int getRowCount() {
           return this.data.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
             Stock stock = this.data.get(rowIndex);
            if (columnIndex == 0) {
                return stock.getStock_id();
            }
            if (columnIndex == 1) {
                return stock.getStockprod_name();
            }
            if (columnIndex == 2) {
                return stock.getAmount();
            }
            if (columnIndex == 3) {
                return stock.getPrice();
            }
            return "";
        }
         @Override
        public String getColumnName(int column) {
            return columnName[column];
        }

        }
    
}

        
