/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectteaminthanin.Menu;

import com.mycompany.projectteaminthanin.Cart;
import com.mycompany.projectteaminthanin.DaoModel.DaoProduct;
import com.mycompany.projectteaminthanin.Point_of_sell;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author SUPAKIT KONGKAM
 */
public class CoffeePanel extends javax.swing.JPanel {

    Point_of_sell POS;

    /**
     * Creates new form CoffeePanel
     */
    public CoffeePanel(Point_of_sell pos) {
        initComponents();
        this.POS = pos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEspressoImg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAmericanoImg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblInthaninAllDayImg = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblCappuccinoImg = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblLatteImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEspressoHot = new javax.swing.JButton();
        btnEspressoIce = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAmericanoHot = new javax.swing.JButton();
        btnAmericanoIce = new javax.swing.JButton();
        btnAllDayHot = new javax.swing.JButton();
        btnAllDayIce = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCappuccinoHot = new javax.swing.JButton();
        btnCappuccinoIce = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblMochaImage = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblInthaninBlendImg = new javax.swing.JLabel();
        btnLatteHot = new javax.swing.JButton();
        btnLatteIce = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMochaHot = new javax.swing.JButton();
        btnMochaIce = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnInthaninBlendHot = new javax.swing.JButton();
        btnInthaninBlendIce = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEspressoImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEspressoImg.setText("EspressoImg");
        lblEspressoImg.setMaximumSize(new java.awt.Dimension(48, 14));
        lblEspressoImg.setMinimumSize(new java.awt.Dimension(48, 14));
        lblEspressoImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEspressoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEspressoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAmericanoImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmericanoImg.setText("AmericanoImg");
        lblAmericanoImg.setMaximumSize(new java.awt.Dimension(48, 14));
        lblAmericanoImg.setMinimumSize(new java.awt.Dimension(48, 14));
        lblAmericanoImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAmericanoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAmericanoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblInthaninAllDayImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInthaninAllDayImg.setText("InthaninAllDayImg");
        lblInthaninAllDayImg.setMaximumSize(new java.awt.Dimension(48, 14));
        lblInthaninAllDayImg.setMinimumSize(new java.awt.Dimension(48, 14));
        lblInthaninAllDayImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInthaninAllDayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInthaninAllDayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCappuccinoImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCappuccinoImg.setText("CappuccinoImg");
        lblCappuccinoImg.setMaximumSize(new java.awt.Dimension(48, 14));
        lblCappuccinoImg.setMinimumSize(new java.awt.Dimension(48, 14));
        lblCappuccinoImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCappuccinoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCappuccinoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLatteImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLatteImg.setText("LatteImg");
        lblLatteImg.setMaximumSize(new java.awt.Dimension(48, 14));
        lblLatteImg.setMinimumSize(new java.awt.Dimension(48, 14));
        lblLatteImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLatteImg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLatteImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setText("Espresso 35฿/50฿");

        btnEspressoHot.setText("Hot");
        btnEspressoHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspressoHotActionPerformed(evt);
            }
        });

        btnEspressoIce.setText("Ice");
        btnEspressoIce.setMaximumSize(new java.awt.Dimension(49, 23));
        btnEspressoIce.setMinimumSize(new java.awt.Dimension(49, 23));
        btnEspressoIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspressoIceActionPerformed(evt);
            }
        });

        jLabel3.setText("Americano 35฿/50฿");

        btnAmericanoHot.setText("Hot");
        btnAmericanoHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmericanoHotActionPerformed(evt);
            }
        });

        btnAmericanoIce.setText("Ice");
        btnAmericanoIce.setMaximumSize(new java.awt.Dimension(49, 23));
        btnAmericanoIce.setMinimumSize(new java.awt.Dimension(49, 23));
        btnAmericanoIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmericanoIceActionPerformed(evt);
            }
        });

        btnAllDayHot.setText("Hot");
        btnAllDayHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllDayHotActionPerformed(evt);
            }
        });

        btnAllDayIce.setText("Ice");
        btnAllDayIce.setMaximumSize(new java.awt.Dimension(49, 23));
        btnAllDayIce.setMinimumSize(new java.awt.Dimension(49, 23));
        btnAllDayIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllDayIceActionPerformed(evt);
            }
        });

        jLabel5.setText("InAllDay 40฿/55฿");

        btnCappuccinoHot.setText("Hot");
        btnCappuccinoHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCappuccinoHotActionPerformed(evt);
            }
        });

        btnCappuccinoIce.setText("Ice");
        btnCappuccinoIce.setMaximumSize(new java.awt.Dimension(49, 23));
        btnCappuccinoIce.setMinimumSize(new java.awt.Dimension(49, 23));
        btnCappuccinoIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCappuccinoIceActionPerformed(evt);
            }
        });

        jLabel2.setText("Cappuccino 45฿/60฿");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMochaImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMochaImage.setText("Mocha");
        lblMochaImage.setMaximumSize(new java.awt.Dimension(48, 14));
        lblMochaImage.setMinimumSize(new java.awt.Dimension(48, 14));
        lblMochaImage.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMochaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMochaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblInthaninBlendImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInthaninBlendImg.setText("InthaninBlendImg");
        lblInthaninBlendImg.setMaximumSize(new java.awt.Dimension(48, 14));
        lblInthaninBlendImg.setMinimumSize(new java.awt.Dimension(48, 14));
        lblInthaninBlendImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInthaninBlendImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInthaninBlendImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnLatteHot.setText("Hot");
        btnLatteHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatteHotActionPerformed(evt);
            }
        });

        btnLatteIce.setText("Ice");
        btnLatteIce.setMaximumSize(new java.awt.Dimension(49, 23));
        btnLatteIce.setMinimumSize(new java.awt.Dimension(49, 23));
        btnLatteIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatteIceActionPerformed(evt);
            }
        });

        jLabel4.setText("Café Latte 50฿/65฿");

        jLabel6.setText("Mocha 50฿/65฿");

        btnMochaHot.setText("Hot");
        btnMochaHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMochaHotActionPerformed(evt);
            }
        });

        btnMochaIce.setText("Ice");
        btnMochaIce.setMaximumSize(new java.awt.Dimension(49, 23));
        btnMochaIce.setMinimumSize(new java.awt.Dimension(49, 23));
        btnMochaIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMochaIceActionPerformed(evt);
            }
        });

        jLabel7.setText("InthaninBlend 60฿/70฿");

        btnInthaninBlendHot.setText("Hot");
        btnInthaninBlendHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInthaninBlendHotActionPerformed(evt);
            }
        });

        btnInthaninBlendIce.setText("Ice");
        btnInthaninBlendIce.setMaximumSize(new java.awt.Dimension(49, 23));
        btnInthaninBlendIce.setMinimumSize(new java.awt.Dimension(49, 23));
        btnInthaninBlendIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInthaninBlendIceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnMochaHot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMochaIce, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnEspressoHot)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEspressoIce, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                                .addComponent(jLabel1)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAmericanoHot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAmericanoIce, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAllDayHot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAllDayIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCappuccinoHot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCappuccinoIce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLatteHot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLatteIce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInthaninBlendHot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInthaninBlendIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEspressoHot)
                    .addComponent(btnEspressoIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAmericanoHot)
                    .addComponent(btnAmericanoIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAllDayHot)
                    .addComponent(btnAllDayIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCappuccinoHot)
                    .addComponent(btnCappuccinoIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLatteHot)
                    .addComponent(btnLatteIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMochaHot)
                    .addComponent(btnMochaIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInthaninBlendHot)
                    .addComponent(btnInthaninBlendIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    DaoProduct daoPro = new DaoProduct();
    private void btnEspressoHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspressoHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(14), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(14).getProductName(),
            amount,
            daoPro.get(14).getPrice() * amount
        });
        POS.total += daoPro.get(14).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnEspressoHotActionPerformed

    private void btnEspressoIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspressoIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(1), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(1).getProductName(),
            amount,
            daoPro.get(1).getPrice() * amount
        });
        POS.total += daoPro.get(1).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnEspressoIceActionPerformed

    private void btnAmericanoHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmericanoHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(15), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(15).getProductName(),
            amount,
            daoPro.get(15).getPrice() * amount
        });
        POS.total += daoPro.get(15).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnAmericanoHotActionPerformed

    private void btnAmericanoIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmericanoIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(2), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(2).getProductName(),
            amount,
            daoPro.get(2).getPrice() * amount
        });
        POS.total += daoPro.get(2).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnAmericanoIceActionPerformed

    private void btnAllDayHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllDayHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(16), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(16).getProductName(),
            amount,
            daoPro.get(16).getPrice() * amount
        });
        POS.total += daoPro.get(16).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnAllDayHotActionPerformed

    private void btnAllDayIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllDayIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(3), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(3).getProductName(),
            amount,
            daoPro.get(3).getPrice() * amount
        });
        POS.total += daoPro.get(3).getPrice() * amount;
        POS.setlblTotal(POS.total);
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnAllDayIceActionPerformed

    private void btnCappuccinoHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCappuccinoHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(17), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(17).getProductName(),
            amount,
            daoPro.get(17).getPrice() * amount
        });
        POS.total += daoPro.get(17).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnCappuccinoHotActionPerformed

    private void btnCappuccinoIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCappuccinoIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(4), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(4).getProductName(),
            amount,
            daoPro.get(4).getPrice() * amount
        });
        POS.total += daoPro.get(4).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnCappuccinoIceActionPerformed

    private void btnLatteHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatteHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(18), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(18).getProductName(),
            amount,
            daoPro.get(18).getPrice() * amount
        });
        POS.total += daoPro.get(18).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnLatteHotActionPerformed

    private void btnLatteIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatteIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(5), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(5).getProductName(),
            amount,
            daoPro.get(5).getPrice() * amount
        });
        POS.total += daoPro.get(5).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnLatteIceActionPerformed

    private void btnMochaHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMochaHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(19), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(19).getProductName(),
            amount,
            daoPro.get(19).getPrice() * amount
        });
        POS.total += daoPro.get(19).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnMochaHotActionPerformed

    private void btnMochaIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMochaIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(6), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(6).getProductName(),
            amount,
            daoPro.get(6).getPrice() * amount
        });
        POS.total += daoPro.get(6).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnMochaIceActionPerformed

    private void btnInthaninBlendHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInthaninBlendHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(20), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(20).getProductName(),
            amount,
            daoPro.get(20).getPrice() * amount
        });
        POS.total += daoPro.get(20).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnInthaninBlendHotActionPerformed

    private void btnInthaninBlendIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInthaninBlendIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }
        POS.cart.add(new Cart(daoPro.get(7), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(7).getProductName(),
            amount,
            daoPro.get(7).getPrice() * amount
        });
        POS.total += daoPro.get(7).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnInthaninBlendIceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllDayHot;
    private javax.swing.JButton btnAllDayIce;
    private javax.swing.JButton btnAmericanoHot;
    private javax.swing.JButton btnAmericanoIce;
    private javax.swing.JButton btnCappuccinoHot;
    private javax.swing.JButton btnCappuccinoIce;
    private javax.swing.JButton btnEspressoHot;
    private javax.swing.JButton btnEspressoIce;
    private javax.swing.JButton btnInthaninBlendHot;
    private javax.swing.JButton btnInthaninBlendIce;
    private javax.swing.JButton btnLatteHot;
    private javax.swing.JButton btnLatteIce;
    private javax.swing.JButton btnMochaHot;
    private javax.swing.JButton btnMochaIce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblAmericanoImg;
    private javax.swing.JLabel lblCappuccinoImg;
    private javax.swing.JLabel lblEspressoImg;
    private javax.swing.JLabel lblInthaninAllDayImg;
    private javax.swing.JLabel lblInthaninBlendImg;
    private javax.swing.JLabel lblLatteImg;
    private javax.swing.JLabel lblMochaImage;
    // End of variables declaration//GEN-END:variables
}
