/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectteaminthanin.Menu;

import com.mycompany.projectteaminthanin.Cart;
import com.mycompany.projectteaminthanin.DaoModel.DaoProduct;
import com.mycompany.projectteaminthanin.Point_of_sell;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author SUPAKIT KONGKAM
 */
public class FruitPanel extends javax.swing.JPanel {

    Point_of_sell POS;

    /**
     * Creates new form FruitPanel
     */
    public FruitPanel(Point_of_sell POS) {
        initComponents();
        this.POS = POS;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBluePeaLemonImg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblPunchImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBluePeaLemonIce = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPunchIce = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBluePeaLemonImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBluePeaLemonImg.setText("Blue PeaImg");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBluePeaLemonImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBluePeaLemonImg, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPunchImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPunchImg.setText("PunchImg");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPunchImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPunchImg, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Blue Pea Lemon 45฿");

        btnBluePeaLemonIce.setText("Ice");
        btnBluePeaLemonIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBluePeaLemonIceActionPerformed(evt);
            }
        });

        jLabel2.setText("Punch 45฿");

        btnPunchIce.setText("Ice");
        btnPunchIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPunchIceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBluePeaLemonIce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btnPunchIce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(482, 482, 482))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBluePeaLemonIce)
                    .addComponent(btnPunchIce))
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
DaoProduct daoPro = new DaoProduct();
    private void btnBluePeaLemonIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBluePeaLemonIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(12), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(12).getProductName(),
            amount,
            daoPro.get(12).getPrice() * amount
        });
        POS.total += daoPro.get(12).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnBluePeaLemonIceActionPerformed

    private void btnPunchIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPunchIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(13), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(13).getProductName(),
            amount,
            daoPro.get(13).getPrice() * amount
        });
        POS.total += daoPro.get(13).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnPunchIceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBluePeaLemonIce;
    private javax.swing.JButton btnPunchIce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBluePeaLemonImg;
    private javax.swing.JLabel lblPunchImg;
    // End of variables declaration//GEN-END:variables
}
