/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectteaminthanin.Menu;

import com.mycompany.projectteaminthanin.Cart;
import com.mycompany.projectteaminthanin.DaoModel.DaoProduct;
import com.mycompany.projectteaminthanin.Point_of_sell;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author SUPAKIT KONGKAM
 */
public class TeaAndCocoaPanel extends javax.swing.JPanel {

    Point_of_sell POS;

    /**
     * Creates new form TeaAndCocoaPanel
     */
    public TeaAndCocoaPanel(Point_of_sell pos) {
        initComponents();
        this.POS = pos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblThaiTeaLatteImg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblGreenTeaImg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCocoaImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnThaiTeaHot = new javax.swing.JButton();
        btnThaiTeaIce = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGreenTeaHot = new javax.swing.JButton();
        btnGreenTeaIce = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnCocoaHot = new javax.swing.JButton();
        btnCocoaIce = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnBlackTeaImg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBlackTeaIce = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblLemonTeaImg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLemonTeaIce = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblThaiTeaLatteImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThaiTeaLatteImg.setText("Thai Tea LatteImg");
        lblThaiTeaLatteImg.setMaximumSize(new java.awt.Dimension(48, 14));
        lblThaiTeaLatteImg.setMinimumSize(new java.awt.Dimension(48, 14));
        lblThaiTeaLatteImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThaiTeaLatteImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThaiTeaLatteImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblGreenTeaImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGreenTeaImg.setText("Green TeaImg");
        lblGreenTeaImg.setMaximumSize(new java.awt.Dimension(48, 14));
        lblGreenTeaImg.setMinimumSize(new java.awt.Dimension(48, 14));
        lblGreenTeaImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGreenTeaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGreenTeaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCocoaImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCocoaImg.setText("CocoaImg");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCocoaImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCocoaImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setText("ThaiTeaLatte 40฿/45฿");

        btnThaiTeaHot.setText("Hot");
        btnThaiTeaHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThaiTeaHotActionPerformed(evt);
            }
        });

        btnThaiTeaIce.setText("Ice");
        btnThaiTeaIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThaiTeaIceActionPerformed(evt);
            }
        });

        jLabel2.setText("GreenTeaLatte 40฿/45฿");

        btnGreenTeaHot.setText("Hot");
        btnGreenTeaHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreenTeaHotActionPerformed(evt);
            }
        });

        btnGreenTeaIce.setText("Ice");
        btnGreenTeaIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreenTeaIceActionPerformed(evt);
            }
        });

        jLabel4.setText("Cocoa 40฿/45฿ ");

        btnCocoaHot.setText("Hot");
        btnCocoaHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocoaHotActionPerformed(evt);
            }
        });

        btnCocoaIce.setText("Ice");
        btnCocoaIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocoaIceActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBlackTeaImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBlackTeaImg.setText("BlackTeaImg");
        btnBlackTeaImg.setMaximumSize(new java.awt.Dimension(48, 14));
        btnBlackTeaImg.setMinimumSize(new java.awt.Dimension(48, 14));
        btnBlackTeaImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBlackTeaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBlackTeaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setText("Black Tea 45฿ ");

        btnBlackTeaIce.setText("Ice");
        btnBlackTeaIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlackTeaIceActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLemonTeaImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLemonTeaImg.setText("Lemon TeaImg");
        lblLemonTeaImg.setMaximumSize(new java.awt.Dimension(48, 14));
        lblLemonTeaImg.setMinimumSize(new java.awt.Dimension(48, 14));
        lblLemonTeaImg.setPreferredSize(new java.awt.Dimension(48, 14));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLemonTeaImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLemonTeaImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel5.setText("Lemon Tea 45฿");

        btnLemonTeaIce.setText("Ice");
        btnLemonTeaIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLemonTeaIceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThaiTeaHot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThaiTeaIce)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGreenTeaHot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGreenTeaIce, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCocoaHot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCocoaIce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBlackTeaIce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btnLemonTeaIce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThaiTeaHot)
                        .addComponent(btnThaiTeaIce))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGreenTeaHot)
                        .addComponent(btnGreenTeaIce))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCocoaHot)
                        .addComponent(btnCocoaIce))
                    .addComponent(btnBlackTeaIce)
                    .addComponent(btnLemonTeaIce))
                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    DaoProduct daoPro = new DaoProduct();
    private void btnThaiTeaHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThaiTeaHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(22), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(22).getProductName(),
            amount,
            daoPro.get(22).getPrice() * amount
        });
        POS.total += daoPro.get(22).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnThaiTeaHotActionPerformed

    private void btnThaiTeaIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThaiTeaIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(8), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(8).getProductName(),
            amount,
            daoPro.get(8).getPrice() * amount
        });
        POS.total += daoPro.get(8).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnThaiTeaIceActionPerformed

    private void btnGreenTeaHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreenTeaHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(21), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(21).getProductName(),
            amount,
            daoPro.get(21).getPrice() * amount
        });
        POS.total += daoPro.get(21).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnGreenTeaHotActionPerformed

    private void btnGreenTeaIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreenTeaIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(24), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(24).getProductName(),
            amount,
            daoPro.get(24).getPrice() * amount
        });
        POS.total += daoPro.get(24).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnGreenTeaIceActionPerformed

    private void btnCocoaHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocoaHotActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(23), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(23).getProductName(),
            amount,
            daoPro.get(23).getPrice() * amount
        });
        POS.total += daoPro.get(23).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnCocoaHotActionPerformed

    private void btnCocoaIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocoaIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(11), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(11).getProductName(),
            amount,
            daoPro.get(11).getPrice() * amount
        });
        POS.total += daoPro.get(11).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnCocoaIceActionPerformed

    private void btnBlackTeaIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlackTeaIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(9), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(9).getProductName(),
            amount,
            daoPro.get(9).getPrice() * amount
        });
        POS.total += daoPro.get(9).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnBlackTeaIceActionPerformed

    private void btnLemonTeaIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLemonTeaIceActionPerformed
        int amount = 0;
        try {
            amount = Integer.parseInt(JOptionPane.showInputDialog("Input Amount : "));
        } catch (java.lang.NumberFormatException e) {
            System.out.println("Cancle");
        }
        if (amount == 0) {
            return;
        }

        POS.cart.add(new Cart(daoPro.get(10), amount));
        POS.getCartModel().addRow(new Object[]{
            daoPro.get(10).getProductName(),
            amount,
            daoPro.get(10).getPrice() * amount
        });
        POS.total += daoPro.get(10).getPrice() * amount;
        POS.setlblTotal(POS.total);
    }//GEN-LAST:event_btnLemonTeaIceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlackTeaIce;
    private javax.swing.JLabel btnBlackTeaImg;
    private javax.swing.JButton btnCocoaHot;
    private javax.swing.JButton btnCocoaIce;
    private javax.swing.JButton btnGreenTeaHot;
    private javax.swing.JButton btnGreenTeaIce;
    private javax.swing.JButton btnLemonTeaIce;
    private javax.swing.JButton btnThaiTeaHot;
    private javax.swing.JButton btnThaiTeaIce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCocoaImg;
    private javax.swing.JLabel lblGreenTeaImg;
    private javax.swing.JLabel lblLemonTeaImg;
    private javax.swing.JLabel lblThaiTeaLatteImg;
    // End of variables declaration//GEN-END:variables
}
